---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: andreikrasnitski/ci

run:
  path: git-concourse-pcf-external-worker-release/ci/scripts/delete-tile.sh

params:
  PCF_URL:
  PCF_USERNAME:
  PCF_PASSWORD:

inputs:
  - name: git-concourse-pcf-external-worker-release-output
  - name: git-concourse-pcf-external-worker-release
  - name: concourse-release
